modmap:
  - name: Wacom Stylus Disable buttons
    device: 
      only: '/dev/input/event5'
    remap:
      BTN_STYLUS: []
      BTN_STYLUS2: []
      #KEY_A: KEY_B

keymap:
  - name: Wacom Remap Stylus Buttons
    device: 
      only: '/dev/input/event5'
    remap:
      BTN_STYLUS-BTN_TOUCH: BTN_RIGHT
      BTN_STYLUS2-BTN_TOUCH: BTN_MIDDLE
